name: Handle issues

on:
  push:
  workflow_dispatch:
  schedule:
    # Every 10 minutes
    - cron: "*/10 * * * *"

permissions: write-all

jobs:
  handle:
    name: Handle Issues

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installing Dependencies and run bot
        run: |
          npm i -g pnpm
          pnpm install

          node discord.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          BOT_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Update Database
        uses: EndBug/add-and-commit@v9
        continue-on-error: true
        with:
          add: .
          message: "Update Reports"
