name: Handle Application Report

on:
  push:
  issues:
    types: [opened]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon

      - name: Start ClamAV daemon
        run: |
          sudo systemctl start clamav-daemon
          sudo systemctl status clamav-daemon || journalctl -xe
          sudo freshclam || true

      - name: Wait for clamd to be ready
        run: |
          for i in {1..10}; do
            nc -zv localhost 3310 && echo "clamd is up!" && exit 0
            echo "Waiting for clamd to start..."
            sleep 2
          done
          echo "clamd did not start in time!" >&2
          exit 1

      - name: Write GitHub event to file
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            fs.writeFileSync("./event.json", JSON.stringify(context.payload));

      - name: Installing Dependencies and run bot
        run: |
          sudo systemctl stop clamav-freshclam.service
          sudo freshclam || true
          sudo systemctl start clamav-freshclam.service

          sudo /etc/init.d/clamav-daemon start

          npm i -g pnpm
          pnpm install

          node issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK_URL }}
